import image1 from "../img/img1.jpeg";
import image2 from "../img/img2.jpeg";
import image3 from "../img/img3.jpeg";
import image4 from "../img/img4.jpeg";
import image5 from "../img/img5.jpeg";
import image6 from "../img/img6.jpeg";
import image7 from "../img/img7.jpeg";
import image8 from "../img/img8.jpeg";
import image9 from "../img/img9.jpeg";
import image10 from "../img/img10.jpeg";
import image11 from "../img/img11.jpeg";
import image12 from "../img/img12.jpeg";
export const data = [
  {
    id: 1,
    title: "Focaccia Ekmeği",
    desc: "Un, su, tuz ve maya ile hazırlnan bu ekmek üzerine çeşitli sebzeler konularak fırına veirilir.",
    image: image1,
    malzeme: [
      "1.PATATES PÜRESİ(PÜRÜZSÜZ)",
      "2.UN",
      "3.SU",
      "4.ZEYTİNYAĞI",
      "5.YAŞ MAYA",
      "6.TUZ",
      "7.SU",
      "8.ZEYTİNYAĞI",
      "9.TAZEBİBERİYE YAPRAKLARI",
      "10.FESLEĞEN YAPRAKLARI",
      "11.ÇERİ DOMATES",
    ],
    gramaj: [
      "750 GR",
      "1.5 GR",
      "750 GR",
      "250 GR",
      "50 GR",
      "25 GR",
      "75 GR",
      "75 GR",
      "ÜZERİ SÜSLEME",
      "ÜZERİ SÜSLEME",
      "ÜZERİ SÜSLEME",
    ],
    hazirlik:
      "Tüm malzemeler kıtcheanid ile hamur karıştırılır. Bolca zeytinyağlanmış 1:1 gastronoma yayılır. Parmak izi verilir. Streçlenip mayalanmaya bırakılır. Tekrar parmak izi verilip buzdolabında mayandırılır. Üzerine olan tüm malzemeler sürülüp ve biberiye fesleğen ile süslenir. Fırında 170 derecede 20-30 dakika pişirilir. Ilıması beklenip servis edilir.",
  },
  {
    id: 7,
    title: "Brokolili Mısır Çorbası",
    desc: "Brokoli ve mısırın krema ile birlşmesi.",
    image: image8,
    malzeme: [
      "1.BROKOLİ ",
      "2.SEBZE SUYU",
      "3.SIVI YAĞ",
      "4.TEREYAĞ",
      "5.SÜT",
      "6.UN",
      "7.HAŞLANMIŞ MISIR",
      "8.ISPANAK",
      "9.TUZ",
      "10.KARABİBER",
      "11.MUSKAT",
    ],
    gramaj: [
      "300 GR",
      "1 L",
      "15 ML",
      "15 GR",
      "80 GR",
      "18 GR",
      "100 GR ",
      "2 DAL",
      "5 GR",
      "5 GR",
      "5 GR",
    ],
    hazirlik:
      "Sıvıyağ tencerede ısıtılıp un ile kavrulur, süt eklenerek beşamel sos kıvamına getirilir ve sebze suyu eklenerek kaynatılır. Karışım laynayınca ince kıyılmış ıspanak yaprakları mısır ve brokoli ilave edilir. Sebzeler yumuşayıncaya kadar pişirilir ve baharatları ilave edilir.",
  },
  {
    id: 5,
    title: "Falafelli Salata",
    desc: "Mevsim yeşillikleri üzerine kızartılmış falafel topları.",
    image: image6,
    malzeme: [
      "1.Haşlanmış nohut",
      "2.Karabuğday unu",
      "3.Yumurta",
      "4.Maydanoz",
      "5.Dereotu",
      "6.Zeytinyağı ",
      "7.Toz Zencefil ",
      "8.Toz Zerdeçal",
      "9.Sarımsak tozu ",
      "10.Karabiber ",
      "11.Kimyon ",
      "12.Tuz ",
    ],
    gramaj: [
      "300 GR",
      "36 GR",
      "2 ADET",
      "1 demet ",
      "1 demet ",
      "60 GR",
      "5 GR",
      "5 GR",
      "5 GR",
      "5 GR",
      "5 GR",
      "5 GR",
    ],
    hazirlik:
      "Nohut haşlanıp blenderdan geçirilir. Üzerine diğer malzemeler eklenip karıştırılırak yoğurulur. Yassı yuvarlak toplar haline getirilir. 180 derece fırında üzeri kızarana dek 15-20dk pişirilir",
  },
  {
    id: 4,
    title: "Humus",
    desc: "Nohutların tahin ile mutheşem bulşması.",
    image: image2,
    malzeme: [
      "1.NOHUT ",
      "2.TAHİN",
      "3.SARIMSAK",
      "4.LİMON SUYU",
      "5.ZEYTİNYAĞI",
      "6.TOZ BİBER ",
      "7.KİMYON",
      "8.TUZ",
    ],
    gramaj: [
      "500 GR",
      "60 ML",
      "4 DİŞ",
      "1 ADET",
      "60 ML",
      "5 GR",
      "5 GR",
      "5 GR",
    ],
    hazirlik:
      "Haşlanmış nohut bir tencereye alınır.Sarımsağın ve nohutların kabukları soyulur, hasşanmış nohutun üstüne sıvı malzemerlimiz olan tahin zeytinyağı limon suyu eklenir. Baharatlar eklenrerek buz ile rondodan geçirilir. Sunum için ayırılan nohutlar ve toz biber ile kızdırılmış yağ gezdirilerek sunum tamamlanır.",
  },
  {
    id: 6,
    title: "Kuşkonmazlı Risotto",
    desc: "Risotto pirincinin beyaz şarap ile buluşması ve kuşkonmaz ile servis edilmesi.",
    image: image7,
    malzeme: [
      "1.Risotto pirinci ",
      "2.Zeytinyağı",
      "3.Soğan (brunoise)",
      "4.Kuşkonmaz",
      "5.Beyaz şarap",
      "6.Sebze suyu ",
      "7.Tereyağı (soğuk) ",
      "8.Parmesan (toz)",
      "9.tuz ",
      "10.Karabiber ",
    ],
    gramaj: [
      "50 gr",
      "15 ml",
      "30 gr",
      "3-4 adet",
      "60 ml",
      "500 ml",
      "20 gr",
      "20 gr",
      "5 gr",
      "5 gr",
    ],
    hazirlik:
      "Soğanı zeytinyağında renk vermeden soteliyoruz. Pirinçleri ekliyoruz ve karıştırarak kavuruyoruz .Beyaz şarabı ekleyip karıştırıyoruz.Sebze suyunu azar azar ekleyerek ve sürekli karıştırarak pişiriyoruz. Ayrı bir yerde kuşkonmazları blanch ediyoruz. Risotto tavasına ekliyoruz.Pirincleri al dente kıvamını aldığında ateşten alıyoruz. Soğuk tereyağı ve parmesan ile bağlayıp servis ediyoruz.",
  },
  {
    id: 2,
    title: "Kızarmış Piriçli Ballı Tavuk",
    desc: "Sweet chili sosu üzerine kızarmış pirinç pilavı, avokadolu elmalı garnetür, lahana turşusu garnetürü, susamlı ballı tavuk ve kızarmış iplikler. ",
    image: image4,
    malzeme: [
      "1.Tavuk göğüsü",
      "2.Yumurta",
      "3.Nişasta ",
      "4.Sarımsak",
      "5.Ketçap",
      "6.Bal",
      "7.Soya sosu",
      "8.Esmer şeker ",
      "9.Susam ",
      "10.Limon",
      "11.Tuz",
      "12.Karabiber",
      "13.Mor lahana turşusu",
      "14.Avokado",
      "15.Yeşil elma",
      "16.Piriç",
      "17.sıvı yağ",
    ],
    gramaj: [
      "250 gr",
      "2 adet",
      "10 gr",
      "2-3 diş",
      "5 gr",
      "15 gr",
      "10 gr",
      "5 gr",
      "5 gr",
      "10 ml",
      "5 gr",
      "5 gr",
      "Üzeri süsleme",
      "1 adet",
      "1 adet",
      "150 gr",
      "30 ml",
    ],
    hazirlik:
      "Tavuğun marinasyonu için nişasta yumurta hazırlanır ve tavuklar eklenir. Geriye kalan malzemeler karıştırmakabına alınır ve sos elde edildir, susamlar kavrularak sosa eklenir. Avokado ve yeşil elma hazırlanır ve yaplimon ve tuzla hazırlanır. Kızarmış pirinç için pirinçler yıkanır ve pişirilir. Pişen pirinçler kızartmak için tavayap eklenir ve verilmek istenilen şekil verildikten sonrakızartma işlemi yapılır. Sunum aşamasında hazırlananher şey tabağa sırayla alınır ve süslemek için acı iplikler kullanıyoruz.",
  },
  {
    id: 3,
    title: "Beyaz Tart",
    desc: "Tart hamurunun içinde pastacı kreams, vişneli dolgusu üst kısmında beyaz çikolata, mevsim meyveleri ve yenilebilir çiçekler.",
    image: image3,
    malzeme: [
      "1.un",
      "2.tereyağ",
      "3.şeker",
      "4.vanilin",
      "5.yumurta",
      "6.süt",
      "7.Beyaz çikolata",
      "8.şeker",
      "9.un ",
      "10.tereyağ",
      "11.kremşanti",
      "12.vişneli sos",
      "13.vişne",
    ],
    gramaj: [
      "250 gr",
      "125 gr",
      "75 gr",
      "1 adet",
      "1 adet",
      "250 ml",
      "30 gr",
      "15 gr",
      "15 gr",
      "15 gr",
      "1 paket",
      "150 gr",
      "200 gr",
    ],
    hazirlik:
      "Hamur için terayağı dışındaki tüm malzemeler yoğurma kabına alınır ve son aşamada soğuk tereyağı eklenir. Dinlenmeye bırakılır. Kreması için süt şeker un ve yumurta tencereye aktarılır kıvam aldıktan sonra vanilya tereyağı eklenir ve kremşanti soğuma aşamasında eklenir. Vişneli sos için ayıklanmış vişneler nişasta ve şeker ile bir tavaya aktarılır ve kıvam alması sağlanır. Beyaz çikolatayı benmari usulü eritiyoruz tart hamurumuzun büyüklüğünde disk halinde donduruyoruz. Tüm malzemeleri bir araya getirerek tabaklama yapıyoruz.",
  },

  {
    id: 8,
    title: "Fıstık Ezmeli Mousse",
    desc: "Fıstık krokanının üstüne ipekse hale getirilmiiş mousse.",
    image: image5,
    malzeme: [
      "1.Fıstık ezmesi",
      "2.Esmer şeker",
      "3.Krema",
      "4.Vanilya",
      "5.Tuz",
      "6.Kremşanti",
      "7.Fıstık tuzsuz",
      "8.Şeker",
    ],
    gramaj: [
      "125 gr",
      "75 gr",
      "125 gr",
      "5 gr",
      "1 tutam",
      "125 gr",
      "125 gr",
      "45 gr",
    ],
    hazirlik:
      "Fıstık ezmesi ve esmer şekeri creaming yapın içine kremayı ve vanilyayı ilave edip karıştırın. Soğuk kremşantiyi mikser yardımıyla çırpıp kabartın ve fıstık ezmeli karışımın içine fold edin. 3 Bir sıkma torbası ya da kaşık yardımı ile bardaklara doldurun. Krokan 1 Fıstıkları tavada kavurun. 2 Şekeri karamel yapın ve ikisini birbirine karıştırın, içine 2 tutam tuzu da ilave edip, bir yağlı silpatın üzerine dökün. Soğuyunca parçalara ayırıp mousseun üzerinde kullanın. ",
  },
  {
    id: 9,
    title: "Narlı Pazı Salata",
    desc: "Pazı yapraklarının lor peyniri ve nar ile buluşması.",
    image: image9,
    malzeme: [
      "1.HAŞLANMIŞ PAZI SAPLARI",
      "2.TULUM PEYNİRİ",
      "3.ZEYTİNYAĞI",
      "4.TUZ",
      "5.KARABİBER",
      "6.PORTAKAL SUYU",
      "7.NAR",
      "8.CEVİZ İÇİ ",
    ],
    gramaj: [
      "125 GR",
      "100 GR",
      "30 GR ",
      "5 GR",
      "5 GR",
      "50 ML",
      "100 GR ",
      "100 GR ",
    ],
    hazirlik:
      "Artan pazı saplarının varsa fazla suyunu iyice sıkın. Orta kalınlıkta olacak şekilde doğrayıp geniş bir kaba alın.Üzerine tulum peyniri, zeytinyağı, tuz, karabiber ve portakal suyu ekleyip güzelce karıştırın.Hazır olan salatayı bir servis kasesine aldıktan sonra bolca nar ve cevizle süsleyerek servis edin.",
  },
  {
    id: 10,
    title: "Gnocchi",
    desc: "Patatese bir İtalyan dokunuşu.",
    image: image10,
    malzeme: [
      "1.haşlanmış patates",
      "2.un",
      "3.toz parmesan peyniri",
      "4.irmik unu",
      "5.yumurta sarısı",
      "6.muskat rendesi",
      "7.Tereyağı",
      "8.taze adaçayı ",
      "9.limon suyu ",
      "10.karabiber ",
      "11.tuz ",
    ],
    gramaj: [
      "250 gr",
      "50 gr",
      "20 gr",
      "30 gr",
      "1/2 adet",
      "1 tutam",
      "40 gr",
      "2 dal ",
      "10 ml",
      "10 gr",
      "10 gr",
    ],
    hazirlik:
      "Bir karıştırma kabına rendelenmiş patates, parmesan, un, irmik unu, karabiber, tuz, yumurta sarısı ve rendelenmiş muskatı ilave edin.Malzemeleri karıştırıp yoğurarak hamur haline getirin.Hamuru streç filme sararak 30 dakika buzdolabında dinlendirin.Dinlenen hamuru hafif un serpilmiş mutfak tezgahına alın. Yuvarlayarak silindir haline getirin ve eşit parçalar halinde kesin.Kesilen parçaları çatal yardımıyla yuvarlayarak şekil verin.Tereyağını bir tavaya ekleyerek eritin.Eriyen tereyağına limon suyu, adaçayı, tuz ve karabiberi ekleyerek karıştırın.70-80 dereceye gelen sos hazır olacaktır.Gnocchileri haşlamak için derin bir tencereye kaynar su ilave edin ve içine bir tutam tuz ekleyin.Haşlanan gnocchiler su yüzeyine çıkacaktır.Gnocchileri tavadaki tereyağlı sosa alın ve 1-2 dk kızartın.Servis tabağına alın ve üzerine toz parmesan ilave ederek sıcak olarak servis edin.",
  },
  {
    id: 11,
    title: "Tavuklu Sezar Salata",
    desc: "Sezar sosunun mevsim yeşillikleri, tavuk ve permesan peyniri ile buluşması.",
    image: image11,
    malzeme: [
      "1.SARIMSAK",
      "2.ZEYTİNYAĞI",
      "3.KONSERVE SARDALYA",
      "4.HARDAL",
      "5.PERMESAN",
      "6.SİRKE",
      "7.PEKMEZ",
      "8.TUZ",
      "9.KARABİBER",
      "10.MARUL",
      "11.SEZAR SOS",
      "12.PARMESAN",
      "13.TAVUK GÖĞÜSÜ",
    ],
    gramaj: [
      "3 DİŞ",
      "30 ML",
      "2 ADET",
      "50 GR",
      "50 GR",
      "20 GR",
      "20 GR",
      "10 GR",
      "10 GR",
      "1 ADET",
      "50 GR",
      "üzeri süsleme",
      "150 gr",
    ],
    hazirlik:
      "Krutonlar için, 3 diş sarımsağı ince ince kıyın. Geniş bir tavada 3 çorba kaşığı zeytinyağını ısıtıp sarımsakları ekleyin. Kısık orta ateşte sarımsaklar kararmadan kızarana kadar kavurun. Böylece sarımsak yağa lezzetini verecek. ·    Sarımsaklar kızardıktan sonra tavadan alın ve küp küp doğradığınız 4 dilim tost ekmeğini ekleyin. Tüm ekmekler yağa bulandıktan sonra altını kısıp iyice kızarıp renk alana kadar kavurun. Üzerine ağız tadınıza göre tuz ve karabiber ekleyin. ·    Sezar salata sosu için, 2,5 adet konserve sardalyanın kılçıklarını çıkartıp incecik kıyın ve geniş bir kaseye koyun.·    Üzerine, 4 çorba kaşığı mayonez, 1 limonun suyu, 1 dolu tatlı kaşığı hardal, 4 çorba kaşığı rende parmesan, 3 diş rende sarımsak, birer tatlı kaşığı sirke ve pekmez, birer çay kaşığı tuz ve karabiber ekleyip karıştırın. Tadına mutlaka bakmayı ihmal etmeyin.·    Gelelim salataya, 1 marulun yapraklarını yıkayıp kurutun. Elinizle kabaca 3-4 parçaya bölerek marul yapraklarını geniş bir kaseye koyun. Üzerine hazırladığınız sosun yaklaşık yarısını dökün. Tüm yapraklar sostan nasibini alana kadar karıştırın ",
  },
  {
    id: 12,
    title: "İnegöl Köfte",
    desc: "İnegöl Köftesinin bulgur pilavı ile yapılan yöresel tadı.",
    image: image12,
    malzeme: [
      "1.dana döş kıyma",
      "2.orta yağlı kuzu kıyma",
      "3.orta boy kuru soğan",
      "4.karbonat",
      "5.tuz",
    ],
    gramaj: ["850 gr", "150 gr", "2 adet", "10 gr", "7-8 gr"],
    hazirlik:
      "Kuru soğanları rendeleyip suyunu sıkınız. Rendelenip suyu sıkılmış kuru soğan, karbonat ve tuzu 10-15 dakika kadar yoğurunuz.İyice yoğrulan köfte harcını buzdolabında kapalı bir kapta bir gece bekletiniz. Buzdolabından çıkarılan köfte harcını 10-15 dakika dinlendirildikten sonra tekrar yoğurunuz. Köfte harcına parmak şekli veriniz. Köfteleri orta ateşte, kızgın tavada ya da çok harlı olmayan ızgarada çevirerek kızartınız.İnegöl köfteyi sumaklı soğan salatası ve piyaz eşliğinde tabak servisi yapınız",
  },
];
